"""add sales return tables

Revision ID: 502ae6b9ed8c
Revises: b464ff592fdd
Create Date: 2026-09-07 11:25:18.894179
"""
from alembic import op
import sqlalchemy as sa


revision = '502ae6b9ed8c'
down_revision = 'b464ff592fdd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_number', sa.String(length=40), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('refund_amount', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_returns_return_date'), 'sales_returns', ['return_date'], unique=False)
    op.create_index(op.f('ix_sales_returns_sales_order_id'), 'sales_returns', ['sales_order_id'], unique=False)
    op.create_index(op.f('ix_sales_returns_tenant_id'), 'sales_returns', ['tenant_id'], unique=False)
    op.create_index('ix_sales_returns_tenant_number', 'sales_returns', ['tenant_id', 'return_number'], unique=True)
    op.create_table('sales_return_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('gst_rate', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('line_total', sa.Float(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['sales_returns.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_return_lines_tenant_id'), 'sales_return_lines', ['tenant_id'], unique=False)
    


def downgrade() -> None:
   
    op.drop_index(op.f('ix_sales_return_lines_tenant_id'), table_name='sales_return_lines')
    op.drop_table('sales_return_lines')
    op.drop_index('ix_sales_returns_tenant_number', table_name='sales_returns')
    op.drop_index(op.f('ix_sales_returns_tenant_id'), table_name='sales_returns')
    op.drop_index(op.f('ix_sales_returns_sales_order_id'), table_name='sales_returns')
    op.drop_index(op.f('ix_sales_returns_return_date'), table_name='sales_returns')
    op.drop_table('sales_returns')
    # ### end Alembic commands ###
