"""add sales quotations

Revision ID: b464ff592fdd
Revises: bd061629327c
Create Date: 2026-09-03 20:27:50.390794
"""
from alembic import op
import sqlalchemy as sa


revision = 'b464ff592fdd'
down_revision = 'bd061629327c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_number', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotations_tenant_id'), 'quotations', ['tenant_id'], unique=False)
    op.create_index('ix_quotations_tenant_number', 'quotations', ['tenant_id', 'quote_number'], unique=True)
    op.create_table('quotation_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('gst_rate', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('line_total', sa.Float(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_lines_tenant_id'), 'quotation_lines', ['tenant_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotation_lines_tenant_id'), table_name='quotation_lines')
    op.drop_table('quotation_lines')
    op.drop_index('ix_quotations_tenant_number', table_name='quotations')
    op.drop_index(op.f('ix_quotations_tenant_id'), table_name='quotations')
    op.drop_table('quotations')
    # ### end Alembic commands ###

