"""add sales e invoice fields

Revision ID: bd061629327c
Revises: 819db5bd6fda
Create Date: 2026-09-03 19:50:19.826433
"""
from alembic import op
import sqlalchemy as sa


revision = 'bd061629327c'
down_revision = '819db5bd6fda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('sales_orders', sa.Column('irn', sa.String(length=64), nullable=True))
    op.add_column('sales_orders', sa.Column('irn_status', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_orders', 'irn_status')
    op.drop_column('sales_orders', 'irn')
    op.create_index('ix_products_tenant_sku', 'products', ['tenant_id', 'sku'], unique=True)
    op.create_unique_constraint('uq_product_bom_tenant_product', 'product_boms', ['tenant_id', 'product_id'])
    op.create_unique_constraint('uq_product_bom_line_component', 'product_bom_lines', ['bom_id', 'component_product_id'])
    # ### end Alembic commands ###
