"""add copilot conversation history

Revision ID: bef59cb90f55
Revises: da4414089c6e
Create Date: 2026-09-09 13:12:20.331810
"""
from alembic import op
import sqlalchemy as sa


revision = 'bef59cb90f55'
down_revision = 'da4414089c6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copilot_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_conversations_conversation_id'), 'copilot_conversations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_copilot_conversations_tenant_id'), 'copilot_conversations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_copilot_conversations_tenant_id'), table_name='copilot_conversations')
    op.drop_index(op.f('ix_copilot_conversations_conversation_id'), table_name='copilot_conversations')
    op.drop_table('copilot_conversations')
    # ### end Alembic commands ###
