"""add finance aging fields

Revision ID: da4414089c6e
Revises: 502ae6b9ed8c
Create Date: 2026-09-08 10:01:37.355156
"""
from alembic import op
import sqlalchemy as sa


revision = 'da4414089c6e'
down_revision = '502ae6b9ed8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('payment_terms_days', sa.Integer(), nullable=True))
    op.add_column('purchase_orders', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('purchase_orders', sa.Column('outstanding', sa.Float(), nullable=True))
    op.add_column('sales_orders', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('sales_orders', sa.Column('outstanding', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_orders', 'outstanding')
    op.drop_column('sales_orders', 'due_date')
    op.drop_column('purchase_orders', 'outstanding')
    op.drop_column('purchase_orders', 'due_date')
    op.drop_column('customers', 'payment_terms_days')
    # ### end Alembic commands ###
