"""add cycle count workflow

Revision ID: ffe3de024c64
Revises: 1a386523d085
Create Date: 2026-08-19 22:43:06.303202
"""
from alembic import op
import sqlalchemy as sa


revision = 'ffe3de024c64'
down_revision = '1a386523d085'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_count_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_count_sessions_status'), 'cycle_count_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_cycle_count_sessions_tenant_id'), 'cycle_count_sessions', ['tenant_id'], unique=False)
    op.create_table('cycle_count_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('system_quantity', sa.Float(), nullable=False),
    sa.Column('counted_quantity', sa.Float(), nullable=True),
    sa.Column('variance', sa.Float(), nullable=True),
    sa.Column('counted_by', sa.Integer(), nullable=True),
    sa.Column('counted_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['counted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['cycle_count_sessions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_count_entries_product_id'), 'cycle_count_entries', ['product_id'], unique=False)
    op.create_index(op.f('ix_cycle_count_entries_session_id'), 'cycle_count_entries', ['session_id'], unique=False)
    op.create_index(op.f('ix_cycle_count_entries_tenant_id'), 'cycle_count_entries', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_products_tenant_sku'), 'products', ['tenant_id', 'sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_products_tenant_sku'), 'products', ['tenant_id', 'sku'], unique=True)
    op.drop_index(op.f('ix_cycle_count_entries_tenant_id'), table_name='cycle_count_entries')
    op.drop_index(op.f('ix_cycle_count_entries_session_id'), table_name='cycle_count_entries')
    op.drop_index(op.f('ix_cycle_count_entries_product_id'), table_name='cycle_count_entries')
    op.drop_table('cycle_count_entries')
    op.drop_index(op.f('ix_cycle_count_sessions_tenant_id'), table_name='cycle_count_sessions')
    op.drop_index(op.f('ix_cycle_count_sessions_status'), table_name='cycle_count_sessions')
    op.drop_table('cycle_count_sessions')
    # ### end Alembic commands ###
